services:
  db:
    image: mysql:5.7
    volumes:
      - ${URL_SITE}_db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    container_name: ${URL_SITE}
    image: luizeof/dockerpress:latest
    working_dir: /var/www/html
    volumes:
      - ${URL_SITE}_files:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}  
      WP_REDIS_HOST: db
      VIRTUAL_HOST: ${URL_SITE}
      LETSENCRYPT_HOST: ${URL_SITE}
      LETSENCRYPT_EMAIL: suporte@agenciamobidick.com.br

volumes:
  ${URL_SITE}_db:
  ${URL_SITE}_files: