version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - banco:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    container_name: ${MYSQL_DATABASE}
    image: luizeof/dockerpress:latest
    working_dir: /var/www/html
    volumes:
      - arquivos:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: 104.207.147.11
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}  
      WP_REDIS_HOST: 104.207.147.11
      VIRTUAL_HOST: ${URL_SITE}
      LETSENCRYPT_HOST: ${URL_SITE}
      LETSENCRYPT_EMAIL: suporte@agenciamobidick.com.br